export const ActionTypes = Object.freeze({
  SESSION_BOOTSTRAP: "SESSION_BOOTSTRAP",
  SESSION_TEARDOWN: "SESSION_TEARDOWN",
  SESSION_ERROR: "SESSION_ERROR",
  CUE_SET: "CUE_SET",
  CUE_DELETE: "CUE_DELETE",
  CUE_JUMP: "CUE_JUMP",
  LOOPER_ARM: "LOOPER_ARM",
  LOOPER_RECORD_START: "LOOPER_RECORD_START",
  LOOPER_RECORD_STOP: "LOOPER_RECORD_STOP",
  LOOPER_CLEAR: "LOOPER_CLEAR",
  FX_TOGGLE: "FX_TOGGLE",
  FX_PARAM_SET: "FX_PARAM_SET",
  MIDI_LEARN_START: "MIDI_LEARN_START",
  MIDI_LEARN_BIND: "MIDI_LEARN_BIND",
  MIDI_LEARN_CANCEL: "MIDI_LEARN_CANCEL",
  UI_PANEL_SET: "UI_PANEL_SET",
  UI_TOGGLE: "UI_TOGGLE"
});
